### ISSUE TITLE
ContentElementPreviewRenderer' not found

### ISSUE THREAD

**Issue by Hobokens** [t3brightside/gallerycontent#1]
After installation of the extension (0.0.1.) I get the following error

`Class 'Brightside\Gallerycontent\Hooks\PageLayoutView\ContentElementPreviewRenderer' not found`

TYPO3 9.5.14

**Comment by t3brightside** [comment]
Hey @Hobokens could it be that dumpautoload is needed in your system?

**Comment by t3brightside** [comment]
Ok, silliest thing ever, broken zip archive in TER. Should be fixed now, 0.0.2 version is out there.
