### ISSUE TITLE
Pagination

### ISSUE THREAD

**Issue by plojewski** [t3brightside/gallerycontent#2]
Hi there, I've got a question. Is it any possibility to override pagination template like this:

`
tt_content.gallerycontent {
    view {
        widget.TYPO3\CMS\Fluid\ViewHelpers\Widget\PaginateViewHelper.templateRootPath = {$gallerycontent.templateRootPath}
    }
}
`
?

**Comment by t3brightside** [comment]
Hey @plojewski 
I'm sure there's a way to change it but can't recall by memory and sadly I have no time to investigate it for now. If you come across a solution you are surely welcome to share.

**Comment by enem-frir** [comment]
Hello, next to the lightbox issue within the news #3 I found another problem:
The pagination doesn't work on the news detail page (extension news). As soon as I want to switch to the next page of the gallery I get the message that the news article doesn't exist anymore.

Maybe you could have a look at this as well for the next release. I guess it would be a nice feature if the gallery would work in news articles.

**Comment by t3brightside** [comment]
Pagination needs to be rewritten using TYPO3 pagination API.
