### ISSUE TITLE
Lightbox not working with extension jn_lighterbox

### ISSUE THREAD

**Issue by enem-frir** [t3brightside/gallerycontent#3]
Hello,

I'm using the jn_lighterbox extension in my project for opening images in a lightbox.

The lightbox itself works correctly with the standard content elements, but unfortunately it seems not to work with your provided extension.

After clicking on an image I get following errors in the console:

> Refused to apply inline style because it violates the following Content Security Policy directive: "style-src 'none'". Either the 'unsafe-inline' keyword, a hash ('sha256-XF40drMRON9Qm0dC4qU9NBiM+fma+ykSbIFIj6R5yb4='), or a nonce ('nonce-...') is required to enable inline execution.

> Refused to apply inline style because it violates the following Content Security Policy directive: "style-src 'none'". Either the 'unsafe-inline' keyword, a hash ('sha256-/GsttfBxdlxoPqvqzTUg3Z8XmEm6Xr9QwYLeYSTCg5o='), or a nonce ('nonce-...') is required to enable inline execution.

> Refused to apply inline style because it violates the following Content Security Policy directive: "style-src 'none'". Either the 'unsafe-inline' keyword, a hash ('sha256-XxG7sjnCImDqnQhrkOlK5r5Y9C0c1p6mDenCs/hlFZg='), or a nonce ('nonce-...') is required to enable inline execution.

Do you have any idea what the problem is? Can you solve this?
Did you test it with another lightbox extension? Maybe I can try to get it to work with that one then.

**Comment by t3brightside** [comment]
Hey, it was never tested or made to run with the default lightbox solution, but shouldn't be hard to change the templates accordingly. It could be that I have time to overlook it for the next release.
