### ISSUE TITLE
Open the pictures with fancybox

### ISSUE THREAD

**Issue by olli1991** [t3brightside/gallerycontent#4]
I want to open the pictures with the extention "fancybox". There es a field for the lightbox class in the Typoscript. I needed to add additional parameters for the fancybox.

I have added this row after row 16 in Resources/Private/Partials/Item.html
{settings.lightboxConfiguration}

and after row 28 in Configuration/TypoScript/setup.typoscript
lightboxConfiguration = {$gallerycontent.lightboxConfiguration}

and after row 18 in Configuration/TypoScript/constants.typoscript
# cat=Gallerycontent/gallerycontent; type=string; label= Lightbox additional configuration
gallerycontent.lightboxConfiguration = data-fancybox=fancybox-41
(dependent of the lightbox you use)

With this changes I can open the pictures with the fancyfox. But I am not sure if this is the best solution.

**Comment by t3brightside** [comment]
If it works for you I guess it should be ok.
